Repository mattermost/awat, pull requests merged in 2022-01, with the labels that each got.

#26 Enhanced initialization
  .circleci/config.yml
  cmd/awat/server.go
  go.mod
  go.sum
  internal/api/api_test.go
  internal/api/context.go
  internal/api/translation.go
  internal/api/upload.go
  internal/supervisor/import.go
  model/client_test.go
Labels: 2: Dev Review

#27 Automate release cut
  .circleci/config.yml
  Makefile
  scripts/release.sh
Labels: kind/chore

#28 Fix/release notes installation
  Makefile
  go.mod
  go.sum
  scripts/push-docker.sh
Labels: kind/bug

#29 Fix release script and CI pipeline
  .circleci/config.yml
  scripts/release.sh
Labels: kind/bug

#30 Improve logging
  internal/slack/translator.go
  internal/supervisor/import.go
  internal/supervisor/translation.go
Labels: 3: Reviews Complete

#32 Validate translation requests
  model/translation_request.go
  model/translation_request_test.go
Labels: 2: Dev Review, kind/feature

#31 Standardize resource creation store logic
  cmd/awat/server.go
  internal/api/api_test.go
  internal/api/store.go
  internal/api/translation.go
  internal/mocks/api/store.go
  internal/store/import.go
  internal/store/migrations.go
  internal/store/store.go
  internal/store/translation.go
  internal/store/upload.go
  internal/supervisor/import.go
  internal/supervisor/translation.go
  model/client_test.go
  model/helpers.go
  model/import.go
  model/translation.go
Labels: 2: Dev Review, kind/bug
